version: '3.8'


services:
  web-app:
    container_name: web-app
    build: ./
    ports:
      - 8000:8000
    networks:
      - app_network
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devops

    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app_network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migrate
    command: ["up"]
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_postgres:

networks:
  app_network:
    driver: bridge

    